services:
  server:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro #this is from the documentation
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    platform: linux/amd64 # had to add this due to the M1 chip
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
# at this point we ran docker-compose run --rm composer create-project --prefer-dist laravel/laravel .
# to build the laravel project

# we then updated the .env file in the laravel proj and run to test
# docker-compose up -d --build server
# we add --build so it will check for code changes

#artisan:
#npm:

